# Database MySQL server para o sistema de gerenciamento de tarefas do FlowTasks
CREATE DATABASE FWTASKS_DBS;
USE FWTASKS_DBS;

# Criação da tabela de usuários
CREATE TABLE USERS(
	USER_ID INT NOT NULL PRIMARY KEY,
    USER_NAME VARCHAR(100) NOT NULL,
    USER_EMAIL VARCHAR(100) NOT NULL,
    USER_PSWD VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

# Criação da tabela de tarefas
CREATE TABLE TASKS(
	TASK_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    TASK TEXT NOT NULL,
    TASK_STATUS ENUM('PENDENTE', "CONCLUIDA") DEFAULT 'PENDENTE',
    DUE_DATE DATE,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

# Criação da tabela de tarefas que foram deletadas
CREATE TABLE DELETED_TASKS(
	DELETED_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TASK_ID INT,
    USER_ID INT NOT NULL,
    TASK_DESCRIPTION TEXT,
    TASK_STATUS VARCHAR(20),
    DELETED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

# Criação de indexes para melhor perfomanance do banco
CREATE INDEX IDX_USER_ID ON TASKS(USER_ID);
CREATE INDEX IDX_TASK_STATUS ON TASKS(TASK_STATUS);
CREATE INDEX IDX_USER_EMAIL ON USERS(USER_EMAIL);